{{- if and .Values.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
{{- if .Values.server.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "techmind.fullname" . }}-server
  labels:
    {{- include "techmind.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      {{- include "techmind.server.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
{{- if and .Values.server.enabled .Values.worker.enabled }}
---
{{- end }}
{{- if .Values.worker.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "techmind.fullname" . }}-worker
  labels:
    {{- include "techmind.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  selector:
    matchLabels:
      {{- include "techmind.worker.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
{{- end }}
