global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'techmind'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - 'techmind-rules.yml'

scrape_configs:
  - job_name: 'techmind-server'
    static_configs:
      - targets: ['techmind-server:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
  - job_name: 'techmind-worker'
    static_configs:
      - targets: ['techmind-worker:9091']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
